version: '3.8'

services:
  api:
    build: ./vehicle_counter/app
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  detector:
    build: .
    command: bash -c "xhost +local:"
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - .:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    depends_on:
      - mongodb

volumes:
  dbdata6:
